#!/bin/bash

# Extract fields from JSON
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')   # capitalize first letter
formatted_height=$(jq -r '.height' data.json | awk '{print $1/10 "m"}')
formatted_weight=$(jq -r '.weight' data.json | awk '{print $1/10 "kg"}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

# Format output
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

