#!/bin/bash

# Extract fields from JSON
NAME=$(jq -r '.name' data.json | sed 's/.*/\u&/')   # capitalize first letter
HEIGHT=$(jq -r '.height' data.json | awk '{print $1/10 "m"}')
WEIGHT=$(jq -r '.weight' data.json | awk '{print $1/10 "kg"}')
TYPE=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

# Format output
echo "$NAME is of type $TYPE, weighs $WEIGHT, and is $HEIGHT tall."

